remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Paul Stephan Portfolio
description: My final project submission for CS499 demonstrating three artifacts to complete the course outcomes
